apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  SMTP_USERNAME: "sweasytech63@gmail.com"
  SMTP_PASSWORD: "ceUnYcexiiRTM7WJ4rWVd"
  SMTP_HOST: "sandbox.smtp.mailtrap.io"
type: Opaque
